### ISSUE TITLE
Compilation Errors with lwip v2

### ISSUE THREAD

**Issue by DrP2016** [akaJes/AsyncPing#1]
Hello,

i really like this library, but i now want to test the new lwip v2 that comes with esp8266 core. The Problem is, that i get two errors that i am not able to solve by myself. It would be nice if somone can take a look at this.

Here is the error log from the Arduino IDE:
`C:\Program Files (x86)\Arduino\libraries\AsyncPing\src\AsyncPing.cpp: In member function 'bool AsyncPing::begin(const IPAddress&, uint8_t, uint32_t)':`

`C:\Program Files (x86)\Arduino\libraries\AsyncPing\src\AsyncPing.cpp:45:67: error: invalid conversion from 'uint8_t (*)(void*, raw_pcb*, pbuf*, ip_addr*) {aka unsigned char (*)(void*, raw_pcb*, pbuf*, ip_addr*)}' to 'raw_recv_fn {aka unsigned char (*)(void*, raw_pcb*, pbuf*, const ip4_addr*)}' [-fpermissive]`

`     raw_recv(ping_pcb, _s_ping_recv, reinterpret_cast<void*>(this));`

`In file included from C:\Program Files (x86)\Arduino\libraries\AsyncPing\src\AsyncPing.h:5:0,`
`                 from C:\Program Files (x86)\Arduino\libraries\AsyncPing\src\AsyncPing.cpp:2:`

`C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266/tools/sdk/lwip2/include/lwip/raw.h:101:18: error:   initializing argument 2 of 'void raw_recv(raw_pcb*, raw_recv_fn, void*)' [-fpermissive]`

`void             raw_recv       (struct raw_pcb *pcb, raw_recv_fn recv, void *recv_arg);`
`C:\Program Files (x86)\Arduino\libraries\AsyncPing\src\AsyncPing.cpp: In member function 'uint8_t AsyncPing::ping_recv(raw_pcb*, pbuf*, ip_addr*)':`

`C:\Program Files (x86)\Arduino\libraries\AsyncPing\src\AsyncPing.cpp:151:69: error: cannot convert 'ip_addr**' to 'const ip4_addr_t* {aka const ip4_addr*}' for argument '2' to 's8_t etharp_find_addr(netif*, const ip4_addr_t*, eth_addr**, const ip4_addr_t**)'`

`         etharp_find_addr(NULL, &addr, &_response.mac, &unused_ipaddr);`

**Comment by farsajik** [comment]
hi friend.after upgrading esp8266 to 2.4.1 i have the same errors.did you solve this problem.thanks
